name: Auto Assign

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      uses: pozil/auto-assign-issue@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: brennobemoura
          numOfAssignee: 1
